disabled_rules:
  - identifier_name
excluded:
  - "KinWallet/Generated Files"
  - "Submodules"
  - "Pods"
opt_in_rules:
  - overridden_super_call
  - toggle_bool
  - empty_count
  - empty_string
  - fatal_error_message
  - file_name
  - first_where
  - modifier_order
  - unused_private_declaration
  # - convenience_type
