language: swift
osx_image: xcode9.3
xcode_project: KinWallet.xcodeproj
xcode_scheme: KinWallet
xcode_sdk: iphonesimulator8.4
before_install:
  - openssl aes-256-cbc -K $encrypted_a280d0435855_key -iv $encrypted_a280d0435855_iv -in secrets.zip.enc -out secrets.zip -d
  - unzip secrets.zip
script:
  - xcodebuild test -scheme KinWallet -destination 'platform=iOS Simulator,name=iPhone 8 Plus'
